version: "3.1"

services:

  nginx:
    image: arm64v8/nginx:1.23-alpine
    container_name: project_test_nginx
    working_dir: /code
    restart: always
    volumes:
      - ../:/code/:consistent
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - fpm
    ports:
      - "8088:80"
    networks:
      - project_test_network

  fpm:
    image: t1nkl/php-alpine:fpm-8.2-arm64v8-swoole
    container_name: project_test_fpm
    working_dir: /code
    restart: always
    volumes:
      - ../:/code/:consistent
    entrypoint: /code/.docker/php-fpm/entrypoint.sh
    links:
      - mysql
    networks:
      - project_test_network
      - project_test_db

  mysql:
      image: arm64v8/mysql:8.0.32
      container_name: project_test_mysql
      restart: always
      environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=project_test_db
      ports:
          - "3308:3306"
      networks:
          - project_test_db

networks:
  project_test_network:
    external: true
  project_test_db:
    external: true
